//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaESapERP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LaESaP Gto ERP")]
        public string ERP_PROYECTO_NOMBRE {
            get {
                return ((string)(this["ERP_PROYECTO_NOMBRE"]));
            }
            set {
                this["ERP_PROYECTO_NOMBRE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ERP_PROYECTO_ConnectionStringTemporal {
            get {
                return ((string)(this["ERP_PROYECTO_ConnectionStringTemporal"]));
            }
            set {
                this["ERP_PROYECTO_ConnectionStringTemporal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-4JE52E7\\SQLEXPRESS;Initial Catalog=ERPLaESap;Integrated Secur" +
            "ity=true")]
        public string ERP_PROYECTO_ConnectionStringDB1 {
            get {
                return ((string)(this["ERP_PROYECTO_ConnectionStringDB1"]));
            }
            set {
                this["ERP_PROYECTO_ConnectionStringDB1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ERP_PROYECTO_strConex_WINLAB_EP {
            get {
                return ((string)(this["ERP_PROYECTO_strConex_WINLAB_EP"]));
            }
            set {
                this["ERP_PROYECTO_strConex_WINLAB_EP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ERP_PROYECTO_PRODUCTION {
            get {
                return ((bool)(this["ERP_PROYECTO_PRODUCTION"]));
            }
            set {
                this["ERP_PROYECTO_PRODUCTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Verdana")]
        public string ERP_PROYECTO_FONT_MAIN {
            get {
                return ((string)(this["ERP_PROYECTO_FONT_MAIN"]));
            }
            set {
                this["ERP_PROYECTO_FONT_MAIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LABORATORIO ESTATAL DE SALUD PÚBLICA DEL ESTADO DE GUANAJUATO")]
        public string ERP_LAB_NOMBRE {
            get {
                return ((string)(this["ERP_LAB_NOMBRE"]));
            }
            set {
                this["ERP_LAB_NOMBRE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Beta Nº 208 Fracc. Industrial Delta Carr. León - Silao KM 7 León, Gto.")]
        public string ERP_LAB_DIRECCION_FULL {
            get {
                return ((string)(this["ERP_LAB_DIRECCION_FULL"]));
            }
            set {
                this["ERP_LAB_DIRECCION_FULL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tel. 01(477) 761-04-09, 761-04-11")]
        public string ERP_LAB_TELEFONOS {
            get {
                return ((string)(this["ERP_LAB_TELEFONOS"]));
            }
            set {
                this["ERP_LAB_TELEFONOS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fax: 01(477) 761-04-08")]
        public string ERP_LAB_FAX {
            get {
                return ((string)(this["ERP_LAB_FAX"]));
            }
            set {
                this["ERP_LAB_FAX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E-mail: laesap@prodigy.net.mx")]
        public string ERP_LAB_EMAIL {
            get {
                return ((string)(this["ERP_LAB_EMAIL"]));
            }
            set {
                this["ERP_LAB_EMAIL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("www.guanajuato.gob.mx")]
        public string ERP_LAB_WWW {
            get {
                return ((string)(this["ERP_LAB_WWW"]));
            }
            set {
                this["ERP_LAB_WWW"] = value;
            }
        }
    }
}
